version: '3.8'

# Minimal Docker Compose for essential development dependencies
# Use docker-compose.dev.yml for full development setup

services:
  # ChromaDB for vector storage
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - ALLOW_RESET=true
    restart: unless-stopped
    container_name: unified-pim-chromadb

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    container_name: unified-pim-redis

volumes:
  chromadb_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: unified-pim-network